annotations_dir: /Users/ruben/data/annotations
db_path: /Users/ruben/data/annotations/annotations.db
stardist_model: /Users/ruben/data/models/stardist-versatile-fluo_dynamic.onnx
cell_det_model: /Users/ruben/data/models/dfine_non_nuclear_ep99_v37.onnx
data_dir: /Users/ruben/data
fov_size: [512, 512]
outline_thickness: 4
outline_color: [0, 255, 0]
region_opacity: 46
detections_color: [255, 0, 0]
